version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: ${MONGO_URI}  # Use uma vari치vel de ambiente para o URI do MongoDB
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}  # Vari치vel de ambiente para o nome de usu치rio do MongoDB
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}  # Vari치vel de ambiente para a senha do MongoDB
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
