# Use uma imagem base do Node.js
FROM node:20-alpine  

# Configura o diretório de trabalho
WORKDIR /lolisp2w/app

# Copia o package.json e o package-lock.json
COPY package*.json ./

# Instala as dependências
RUN npm install --production

# Copia o restante dos arquivos da aplicação
COPY . .

# Exponha a porta que a aplicação usa
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["npm", "start"]
